export const SIGNS = [
  "Aries", "Tauro", "Géminis", "Cáncer",
  "Leo", "Virgo", "Libra", "Escorpio",
  "Sagitario", "Capricornio", "Acuario", "Piscis",
] as const

export type Sign = (typeof SIGNS)[number]

export const SIGN_DATES: Record<Sign, string> = {
  Aries: "21 mar — 19 abr",
  Tauro: "20 abr — 20 may",
  Géminis: "21 may — 20 jun",
  Cáncer: "21 jun — 22 jul",
  Leo: "23 jul — 22 ago",
  Virgo: "23 ago — 22 sep",
  Libra: "23 sep — 22 oct",
  Escorpio: "23 oct — 21 nov",
  Sagitario: "22 nov — 21 dic",
  Capricornio: "22 dic — 19 ene",
  Acuario: "20 ene — 18 feb",
  Piscis: "19 feb — 20 mar",
}

export const COLORS = [
  "Turquesa nuclear", "Morado existencial", "Naranja psicodélico",
  "Verde aliensígena", "Rosa chicle", "Gris incertidumbre",
  "Amarillo amanecer con resaca", "Azul profundo como tu crisis",
  "Plateado brillante", "Violeta cósmico", "Rojo intenso",
  "Blanco fantasma", "Lima ácido", "Coral quemado",
  "Oro decadente", "Índigo misterioso",
]

export const ANIMALS = [
  "Una paloma que pelea con su propio reflejo",
  "Un perro que se asusta con su propio pedo",
  "Un gato que juzga tus decisiones desde el refrigerador",
  "Una hormiga que llegó temprano a la fila del banco",
  "Un koala que siempre tiene sueño pero no duerme",
  "Un pingüino con crisis de mediana edad",
  "Una llama que escupe verdades incómodas",
  "Un erizo que abraza con precaución",
  "Un búho que vio cosas que no debía",
  "Un flamenco parado en una pata mientras overthinkea",
  "Una nutria que perdió su piedra favorita",
  "Un mapache que vive al límite",
  "Una ardilla con TDAH",
  "Un hipopótamo sensible",
  "Un murciélago que chocó con todo",
  "Una gaviota que te mira feo",
  "Un camaleón que no sabe qué color ponerle a su vida",
  "Un zorro que le roba cosas a sus amigos como talla",
  "Una oveja que cuenta humanos para dormir",
  "Un delfín que hace bromas pesadas",
]

export const FOODS = [
  "Completo italiano con extra de todo", "Sushi a las 3am",
  "Empanada de pino", "Mote con huesillo",
  "papas fritas con cariño", "Porotos con riendas",
  "Sopaipilla pasá", "Cazuela de la abuela",
  "Chorrillana para dos", "Terremoto",
  "Helado en invierno", "Pizza con piña (porque eres un caos)",
  "completos a la salida del carrete", "Ceviche imposible",
  "Pastel de choclo", "Calzones rotos",
  "Alfajor artesanal", "Mecánico",
  "Pan con palta", "Churros con manjar",
]

export const SONGS = [
  "We Are the Champions — Queen (pero desafinando)",
  "Tusa — Karol G (en tu momento más dramático)",
  "Bohemian Rhapsody — a todo volumen en la ducha",
  "Gasolina — Daddy Yankee (para motivarte a comprar)",
  "Someone Like You — Adele (llanto incluido)",
  "Sandía — Dyablo",
  "Amárrame — Mon Laferte",
  "El Amor Después del Amor — Fito Páez",
  "El Baile del Perrito — por enésima vez",
  "Rocket Man — Elton John (muy apropiado)",
  "La Vida es un Carnaval — para convencerte",
  "Crimen — Gustavo Cerati",
  "Dueles — Jesse & Joy",
  "Flaca — Andrés Calamaro",
  "La Copa de la Vida — porque hoy puedes",
  "Yo No Sé Mañana — Luis Enrique (filosófico)",
  "Gracias a la Vida — Violeta Parra (versión nostálgica)",
  "Mi Matamoros Querido — en una fonda imaginaria",
  "Elgigadget — ritmo pegajoso que no te sacarás",
  "Música de ascensor mientras esperas",
]

export const MESSAGES = [
  '"Llegué" — 3 horas después de lo acordado',
  '"Oye, ¿y la plata que te presté?"',
  '"Hoy sí voy al gym" (no vas a ir)',
  '"Te veo a las 8" — aparece a las 9:15',
  '"Es cortito" — miente como respira',
  '"Ya estoy en camino" — en la ducha todavía',
  '"Dale, una hora más" — amanece',
  '"Está todo bien" — no está nada bien',
  '"Te juro que esta es la última"',
  '"No tengo hambre" — pide todo el menú',
  '"Son solo 5 minutos"',
  '"Mañana empiezo la dieta"',
  '"Te lo devuelvo mañana" (día del pico)',
  '"Estoy bien" *tiene crisis existencial*',
  '"Vamos a hacer algo productivo" *ve memes*',
]

export const PEOPLE_TO_AVOID = [
  "El que dice 'es cortito'",
  "Tu ex (por amor propio, no lo hagas)",
  "El amigo que siempre pide prestado",
  "El compañero que habla de política en el café",
  "La persona que te dice 'tranquilo' cuando hay que preocuparse",
  "El que te manda audios de 5 minutos",
  "El tío que hace chistes malos en reuniones",
  "El vendedor que te sigue en la tienda",
  "La que te dice 'te tengo una noticia' sin contexto",
  "El que responde 'jaja' a todo",
  "El pesado que dice 'yo sé de esto' sin saber",
  "La amiga que te dice 'te lo dije'",
  "El que pone música sin preguntar",
  "La persona que te habla sin café de por medio",
  "El del celu con volumen en el micro",
]

export const OBJECTS = [
  "Una taza con forma de nube", "Un lápiz que perdió su tapa",
  "Una cuchara doblada de tanto revolver café",
  "Un calcetín huérfano", "Un cargador que funciona solo en cierta posición",
  "Una bolsa de té usada", "Una pulsera de la amistad de 2010",
  "Un llavero que no sabes de qué llave es",
  "Una agenda del año pasado", "Un parche de tela random",
  "Una moneda de otro país en tu bolsillo",
  "Un imán de refrigerador con mensaje motivacional",
  "Una goma de borrar que ya no borra",
  "Un posavasos de un bar que no recuerdas",
  "Un folleto de algo que nunca harás",
  "Un tarro vacío que guardas 'por si acaso'",
  "Una foto borrosa que te da nostalgia",
  "Un pitillo reutilizable que perdiste y encontraste",
  "Una caja de fósforos con un solo fósforo",
  "Una nota adhesiva con un número ilegible",
]

export const PREDICTION_TEMPLATES = [
  "Hoy {situacion}. {consecuencia}",
  "El universo dice que {situacion}. {consejo}",
  "Las estrellas anuncian: {situacion}. {consecuencia}",
  "Mercurio retrógrado está {situacion_loca}, así que {consejo}",
  "Hoy {situacion}. Pero tranquile, {consecuencia}",
  "Al despertar, {situacion}. {consejo}",
  "Tu horóscopo de hoy: {situacion}. Y probablemente {consecuencia}",
  "El cosmos te sugiere {situacion_urgente}. Además, {consecuencia}",
  "Hoy es un día para {situacion}. Porque {consecuencia}",
  "Predicción cósmica: {situacion}. Así que {consejo}",
]

export const SITUATIONS = [
  "vas a llegar tarde a algo importante y culparás al tránsito",
  "te vas a acordar de algo vergonzoso que hiciste hace 10 años",
  "vas a tener una conversación incómoda en el ascensor",
  "vas a quemar la comida y pedir delivery fingiendo que lo cocinaste",
  "te vas a tropezar con nada delante de alguien que te gusta",
  "vas a decir 'sí' a un plan que no quieres hacer",
  "te vas a quedar dormido con la luz prendida",
  "vas a mandar un mensaje al chat equivocado",
  "vas a gastar plata en algo que no necesitas pero te hace feliz",
  "vas a tener una revelación existencial en la ducha",
  "alguien te va a decir 'cambiaste' y no sabrás si es bueno o malo",
  "vas a tratar de hacer dos cosas a la vez y fallar en ambas",
  "te va a dar hambre justo después de lavarte los dientes",
  "vas a guardar un meme y no enviarlo a nadie",
  "vas a buscar tus llaves mientras las tienes en la mano",
  "vas a prometer que hoy te acuestas temprano y verás una serie hasta las 4am",
  "vas a abrir el refrigerador cinco veces sin saber qué buscas",
  "vas a sonreírle a un desconocido por error y será incómodo",
  "vas a cantar una canción y poner los dedos en la voz sin querer",
  "vas a tener una discusión con alguien que no está en la habitación",
  "vas a comprar algo solo porque está en oferta",
  "vas a posponer una tarea importante por ver un video de un animal haciendo algo tonto",
  "vas a intentar ser productivo y terminarás viendo fotos de tu ex",
  "vas a tener hambre emocional y confundirla con hambre real",
  "vas a hacer un plan genial y cancelarlo a última hora",
  "vas a decir 'no voy a tomar' y terminarás cantando rancheras",
  "vas a tener un sueño tan raro que te marcará el día",
  "vas a perder algo que estaba en tu mano",
  "vas a prometer que vas al gym y pagar la mensualidad sin ir",
  "vas a tener un malentendido épico por mensaje de texto",
]

export const SITUACIONES_LOCAS = [
  "haciendo malabares con tus responsabilidades",
  "tomando café frío porque no te dio tiempo de calentarlo",
  "celebrándole algo a alguien que no sabes qué es",
  "poniéndote metas que sabes que no cumplirás",
  "cobrándote caro algo que hiciste mal",
  "planificando tu próxima siesta",
  "haciéndote el sorprendido con una noticia que ya sabías",
  "jubilándose anticipadamente de tus responsabilidades",
  "en modo avión con tu vida emocional",
  "cobrando comisión por cada mala decisión que tomes",
]

export const SITUACIONES_URGENTES = [
  "evitar discusiones políticas en la mesa familiar",
  "no revisar el Whatsapp de tu ex aunque sea lunes",
  "salir de tu casa aunque sea para comprar pan",
  "responder los mensajes que llevan días en visto",
  "ordenar tu cuarto antes de que alguien lo vea",
  "cobrarle a ese amigo que debe plata desde enero",
  "no comprar cosas online cuando estás estresado",
  "dejar de posponer la llamada al banco",
  "decir 'no' sin culpa al menos una vez",
  "tomar agua antes de enojarte por tonteras",
]

export const CONSEQUENCES = [
  "al menos tendrás una buena anécdota",
  "peor podría ser, podrías ser funcionario público",
  "pero hey, el café está rico",
  "podría ser peor: podrías tener reunión a las 8am",
  "pero nadie lo vio, así que no pasó",
  "y lo peor es que te reirás solo",
  "pero mañana será otro día con otros problemas",
  "y lo volverás a hacer sin aprender la lección",
  "pero al menos no te quedó el hilo del cepillo en la boca",
  "podría ser peor: podrías haberlo publicado en redes",
  "pero te ves bien haciéndolo, así que ganas",
  "y así sucesivamente hasta el jueves",
  "pero el cosmos te quiere, solo está de humor raro",
  "y con un poco de suerte, nadie se da cuenta",
  "pero hey, eres humano, no un robot perfecto",
  "y esa es tu cruz cósmica de esta semana",
  "pero al menos no fue en vivo y en directo",
  "y la vida sigue, aunque duela la cartera",
  "pero el fin de semana promete",
  "y todo por no haber dormido bien",
]

export const ADVICE = [
  "respira profundo y finge que tienes el control",
  "tómate un café antes de hablar con humanos",
  "dale like a tus propias fotos, te lo mereces",
  "ponte los auriculares y haz como que trabajas",
  "revisa dos veces antes de enviar ese mensaje",
  "si no sabes qué hacer, ponte a bailar",
  "llama a tu mamá, siempre funciona",
  "no tomes decisiones importantes después de las 11pm",
  "come algo rico, el estómago feliz arregla todo",
  "si te invitan a algo, di que sí aunque te dé pereza",
  "mírate al espejo y di 'estoy increíble' hasta que funcione",
  "pon música que te haga sentir en una película",
  "no respondas con el corazón en la mano, usa la razón",
  "si puedes posponerlo, probablemente no era urgente",
  "usa ropa cómoda, el universo no está mirando tu outfit",
  "no le des más scroll, ya viste suficiente internet por hoy",
  "báñate aunque no tengas planes, es terapéutico",
  "escribe lo que sientes aunque después lo borres",
  "abre la ventana, el aire fresco arregla perspectivas",
  "ríete de ti mismo, nadie más lo hará tan bien",
]

export const ABSURD_PHRASES = [
  "Hoy descubrirás que el problema nunca fue Mercurio retrógrado... eras tú llegando tarde.",
  "Hay un 87% de probabilidades de que abras el refrigerador cinco veces sin saber qué buscas.",
  "Hoy tu paciencia tendrá la duración de un video de TikTok.",
  "El universo te debe plata y no piensa pagarte.",
  "Tu suerte hoy es como WiFi en el metro: existe pero no funciona.",
  "Si hoy sientes que todo está mal, tómate un juguito y vuelve a intentarlo.",
  "Hoy es un buen día para no mandar ese mensaje. Guarda el teléfono.",
  "Tu ángel de la guarda está de huelga. Te toca improvisar.",
  "Hoy las probabilidades están a tu favor... si estás en tu casa viendo Netflix.",
  "El cosmos te recomienda quedarte en cama. No es floera, es astrología.",
  "Hoy te levantarás con energía, pero se te olvidará para qué.",
  "Las estrellas dicen que hoy te van a interrumpir mientras comes.",
  "Tu destino hoy: gastar plata en algo que no sabías que necesitabas.",
  "Hoy es día de cosechar lo que sembraste... o de cosechar lo que sembró otro.",
  "El horóscopo de hoy fue escrito por una IA con crisis existencial.",
  "Si Mercurio retrógrado te está afectando, espera a conocer a Marte en picada.",
  "Hoy podrías tener un momento de claridad... justo antes de dormirte.",
  "Las cartas dicen que hoy es buen día para improvisar. No planifiques nada.",
  "Hoy el universo te dice: 'relájate, no es tan serio'.",
  "Tu predicción de hoy: probablemente sobrevivirás, pero no ileso.",
]

export const EASTER_EGGS = [
  {
    title: "⚠ ERROR EN EL UNIVERSO",
    message: "Hoy el destino renunció.\nVuelve mañana.",
    emoji: "💀",
  },
  {
    title: "🔮 SEÑAL PERDIDA",
    message: "Mercurio está haciendo cualquier cosa.\nNo podemos garantizar absolutamente nada.",
    emoji: "📡",
  },
  {
    title: "🏖️ VACACIONES CÓSMICAS",
    message: "El cosmos está de vacaciones.\nImprovisa.",
    emoji: "🌴",
  },
  {
    title: "🤷 SIN RESPUESTA",
    message: "Hoy el algoritmo tampoco sabe qué haces con tu vida.\nBuena suerte.",
    emoji: "🌀",
  },
]
